### ISSUE TITLE
preprocessing script

### ISSUE THREAD

**Issue by wellescastro** [felixriese/CNN-SoilTextureClassification#1]
Hi! I'm wondering if you have plans on releasing the preprocessing script for reproduction of the texture classification experiments. That would be grateful for baseline experiments. Thanks in advance and great work!

**Comment by felixriese** [comment]
Hi @wellescastro, thank you for your proposal. We will consider publishing the preprocessing script as soon as the publication got accepted. Cheers, Felix

**Comment by wellescastro** [comment]
Hi @felixriese. That's great, I hope you get your acceptance and I'm looking forward to the release of the preprocessing script.

**Comment by felixriese** [comment]
All processing scripts can be found in this repository: "LUCAS Soil Texture Processing Scripts"

https://github.com/felixriese/lucas-processing
